In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from astropy.cosmology import Planck18 as cosmo
from astropy import units as u, constants as c
import astropy.cosmology.units as cu

In [2]:
meta = pd.read_csv("ecle-metadata.csv")
meta

,name,ra,ra_unit,dec,dec_unit,coord_bibcode,ecl_discovery_date,discovery_date,discovery_date_format,discovery_date_bibcode,redshift,redshift_bibcode,classification,classification_bibcode,radio_data,radio_data_comment,otter,otter_comments,comment
0,2019qiz,04:46:37.880,hour,-10:13:34.90,degree,2019TNSTR1857....1F,2020-12-15,2458745.9998032,JD,2019TNSTR1857....1F,0.015100,2019TNSTR1857....1F,TDE,2019TNSCR1921....1S,True,"Kate (very good radio dataset, still need to a...",True,good uvoir dataset,Uploader:Noah Franz | Email: nfranz@arizona.edu
1,SDSS_J0748,07:48:20.6668,hour,+47:12:14.2648,degree,2024MNRAS.535.1095C,2004-02-20,2004-02-20,iso,2024MNRAS.528.7076C,0.061600,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,some xray data is available,Uploader:Noah Franz | Email: nfranz@arizona.edu
2,SDSS_J0807,08:07:27.3157,hour,+14:05:37.0892,degree,2024MNRAS.535.1095C,2005-11-08,2005-11-08,iso,2024MNRAS.528.7076C,0.073800,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
3,SDSS_J0938,09:38:01.6376,hour,+13:53:17.0423,degree,2024MNRAS.535.1095C,2006-12-23,2006-12-23,iso,2024MNRAS.528.7076C,0.101000,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,"Kate, VLASS",False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
4,SDSS_J0952,09:52:09.5629,hour,+21:43:13.2979,degree,2024MNRAS.535.1095C,2005-12-30,2005-12-30,iso,2024MNRAS.528.7076C,0.079500,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,some xray data is available,Uploader:Noah Franz | Email: nfranz@arizona.edu
5,SDSS_J1055,10:55:26.4177,hour,+56:37:13.1010,degree,2024MNRAS.535.1095C,2002-04-09,2002-04-09,iso,2024MNRAS.528.7076C,0.074000,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,"Kate, VLASS",False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
6,SDSS_J1207,12:07:19.8102,hour,+24:11:55.8789,degree,2024MNRAS.535.1095C,2008-01-19,2008-01-19,iso,2024MNRAS.528.7076C,0.050300,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
7,SDSS_J1241,12:41:34.2561,hour,+44:26:39.2636,degree,2024MNRAS.535.1095C,2004-02-27,2004-02-27,iso,2024MNRAS.528.7076C,0.041900,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS, 4 other observations from other p...",False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
8,SDSS_J1247,12:47:26.3719,hour,+07:05:25.0809,degree,2024MNRAS.535.1095C,2006-05-21,2006-05-21,iso,2024MNRAS.528.7076C,0.104000,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
9,SDSS_J1342,13:42:44.4150,hour,+05:30:56.1451,degree,2024MNRAS.535.1095C,2002-04-09,2002-04-09,iso,2024MNRAS.528.7076C,0.036500,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,WISE data from Wang+18,Uploader:Noah Franz | Email: nfranz@arizona.edu
10,SDSS_J1350,13:50:01.4946,hour,+29:16:09.6460,degree,2024MNRAS.535.1095C,2006-04-23,2006-04-23,iso,2024MNRAS.528.7076C,0.077700,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,some xray data is available,Uploader:Noah Franz | Email: nfranz@arizona.edu
11,SDSS_J1402,14:02:04.7560,hour,+29:39:46.8759,degree,2024MNRAS.535.1095C,2007-03-19,2007-03-19,iso,2024MNRAS.528.7076C,0.196000,2024MNRAS.528.7076C,Unkown?,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
12,SDSS_J1459,14:59:26.0676,hour,+40:45:38.5508,degree,2024MNRAS.535.1095C,2004-05-21,2004-05-21,iso,2024MNRAS.528.7076C,0.151000,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
13,SDSS_J1715,17:15:04.2893,hour,+56:47:15.8404,degree,2024MNRAS.535.1095C,2000-09-01,2000-09-01,iso,2024MNRAS.528.7076C,0.191000,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
14,SDSS_J2220,22:20:55.7312,hour,-07:53:17.8464,degree,2024MNRAS.535.1095C,2001-10-21,2001-10-21,iso,2024MNRAS.528.7076C,0.149000,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
15,SDSS_J1458,14:58:49.7267,hour,+19:10:33.5109,degree,2024MNRAS.535.1095C,2008-03-14,2008-03-14,iso,2024MNRAS.535.1095C,0.268000,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,VLASS,True,WISE data from Wang+18,Uploader:Noah Franz | Email: nfranz@arizona.edu
16,SDSS_J1238,12:38:29.5894,hour,+18:52:37.5554,degree,2024MNRAS.535.1095C,2008-01-16,2008-01-16,iso,2024MNRAS.535.1095C,0.253000,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
17,AT2017gge,16:20:34.99,hour,+24:07:26.5,degree,2022MNRAS.517...76O,2018-03-09,2457968.8499884,JD,2017TNSTR.895....1T,0.066500,2022MNRAS.517...76O,TDE,2022MNRAS.517...76O,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
18,AT2022fpx,15:31:03.698,hour,+53:24:19.13,degree,2022TNSTR.836....1T,2022-08-05,2459670.01981,JD,2022TNSTR.836....1T,0.073000,2022TNSCR1771....1P,TDE,2022TNSCR1771....1P,True,VLASS,True,no phot,Uploader:Noah Franz | Email: nfranz@arizona.edu
19,AT2022upj,00:23:56.86,hour,-14:25:23.4,degree,2024MNRAS.535.1095C,2022-11-02,2459822.878,JD,2022TNSTR2690....1F,0.054000,2024MNRAS.535.1095C,TDE,2024MNRAS.535.1095C,True,VLASS,True,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
20,AT2021dms,03:21:24.069,hour,-11:08:45.71,degree,2024MNRAS.528.4775H,2021-08-13,2459266.645706,JD,2021TNSTR.542....1F,0.031102,2024MNRAS.528.4775H,TDE,2024MNRAS.528.4775H,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
21,AT2018bcb,22:43:42.871,hour,-16:59:08.49,degree,2020MNRAS.494.2538N,2018-05-13,2458235.62,JD,2018TNSTR.555....1B,0.119200,2020MNRAS.494.2538N,TDE,2020MNRAS.494.2538N,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
22,AT2020vdq,10:08:53.44,hour,+42:43:00.22,degree,2020TNSTR3060....1N,2022-02-06,2459126.9916204,JD,2020TNSTR3060....1N,0.045000,2023arXiv231003782S,TDE,2023arXiv231003782S,True,VLASS,True,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
23,AT2021qth,20:11:38.914,hour,-21:09:36.83,degree,2021TNSTR2141....1F,2022-05-26,2459382.9156134,JD,2021TNSTR2141....1F,0.080500,2023ApJ...955L...6Y,TDE,2023ApJ...955L...6Y,True,VLASS,True,no phot,Uploader:Noah Franz | Email: nfranz@arizona.edu
24,AT2021acak,10:34:47.99,hour,+15:29:22.42,degree,2023RAA....23b5012L,2022-04-23,2459510.12,JD,2021TNSTR3613....1T,0.136000,2023RAA....23b5012L,TDE,2023RAA....23b5012L,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
25,AT2018dyk,15:33:08.015,hour,+44:32:08.20,degree,2018TNSTR.987....1F,2018-08-08,2458269.81,JD,2018TNSTR.987....1F,0.037000,2018TNSCR1182....1H,TDE,2018TNSCR1182....1H,True,VLASS,True,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
26,AT2018gn,01:46:42.45,hour,+32:30:29.30,degree,2018TNSTR..58....1K,2022-06-29,2458132.61,JD,2018TNSTR..58....1K,0.037500,2024ApJ...966..136W,TDE,2024ApJ...966..136W,True,VLASS,True,good optical,Uploader:Noah Franz | Email: nfranz@arizona.edu

In [3]:
def redshift_limit(flux, lum):
    lum_dist = np.sqrt(lum / (4*np.pi*flux)).to(u.Mpc)
    return lum_dist.to(cu.redshift, cu.redshift_distance(cosmo, kind="luminosity"))

In [4]:
vlass_flux_limit = 500*u.uJy * 5*u.GHz
newtownian_outflow_luminosity = 1e38*u.erg/u.s
relativistic_outflow_luminosity = 5e40*u.erg/u.s
off_axis_jet_luminosity = 1e39*u.erg/u.s

newtownian_redshift_limit = redshift_limit(vlass_flux_limit, newtownian_outflow_luminosity)
relativistic_redshift_limit = redshift_limit(vlass_flux_limit, relativistic_outflow_luminosity)
off_axis_jet_redshift_limit = redshift_limit(vlass_flux_limit, off_axis_jet_luminosity)

print(rf"VLASS can detect newtownian outflows at $z \lesssim {newtownian_redshift_limit.value:.2f}$")
print(rf"VLASS can detect relativistic outflows at $z \lesssim {relativistic_redshift_limit.value:.2f}$")
print(rf"VLASS can detect off-axis relativistic outflows at $z \lesssim {off_axis_jet_redshift_limit.value:.2f}$")

VLASS can detect newtownian outflows at $z \lesssim 0.04$
VLASS can detect relativistic outflows at $z \lesssim 0.66$
VLASS can detect off-axis relativistic outflows at $z \lesssim 0.12$

In [5]:
meta[meta.redshift < newtownian_redshift_limit]

,name,ra,ra_unit,dec,dec_unit,coord_bibcode,ecl_discovery_date,discovery_date,discovery_date_format,discovery_date_bibcode,redshift,redshift_bibcode,classification,classification_bibcode,radio_data,radio_data_comment,otter,otter_comments,comment
0,2019qiz,04:46:37.880,hour,-10:13:34.90,degree,2019TNSTR1857....1F,2020-12-15,2458745.9998032,JD,2019TNSTR1857....1F,0.015100,2019TNSTR1857....1F,TDE,2019TNSCR1921....1S,True,"Kate (very good radio dataset, still need to a...",True,good uvoir dataset,Uploader:Noah Franz | Email: nfranz@arizona.edu
9,SDSS_J1342,13:42:44.4150,hour,+05:30:56.1451,degree,2024MNRAS.535.1095C,2002-04-09,2002-04-09,iso,2024MNRAS.528.7076C,0.036500,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,WISE data from Wang+18,Uploader:Noah Franz | Email: nfranz@arizona.edu
20,AT2021dms,03:21:24.069,hour,-11:08:45.71,degree,2024MNRAS.528.4775H,2021-08-13,2459266.645706,JD,2021TNSTR.542....1F,0.031102,2024MNRAS.528.4775H,TDE,2024MNRAS.528.4775H,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
25,AT2018dyk,15:33:08.015,hour,+44:32:08.20,degree,2018TNSTR.987....1F,2018-08-08,2458269.81,JD,2018TNSTR.987....1F,0.037000,2018TNSCR1182....1H,TDE,2018TNSCR1182....1H,True,VLASS,True,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
26,AT2018gn,01:46:42.45,hour,+32:30:29.30,degree,2018TNSTR..58....1K,2022-06-29,2458132.61,JD,2018TNSTR..58....1K,0.037500,2024ApJ...966..136W,TDE,2024ApJ...966..136W,True,VLASS,True,good optical,Uploader:Noah Franz | Email: nfranz@arizona.edu

In [6]:
vla_flux_limit = 30*u.uJy * 5*u.GHz
newtownian_outflow_luminosity = 1e38*u.erg/u.s
relativistic_outflow_luminosity = 5e40*u.erg/u.s
off_axis_jet_luminosity = 1e39*u.erg/u.s

newtownian_redshift_limit = redshift_limit(vla_flux_limit, newtownian_outflow_luminosity)
relativistic_redshift_limit = redshift_limit(vla_flux_limit, relativistic_outflow_luminosity)
off_axis_jet_redshift_limit = redshift_limit(vla_flux_limit, off_axis_jet_luminosity)

print(rf"VLA can detect newtownian outflows at $z \lesssim {newtownian_redshift_limit.value:.2f}$")
print(rf"VLA can detect relativistic outflows at $z \lesssim {relativistic_redshift_limit.value:.2f}$")
print(rf"VLA can detect off-axis relativistic outflows at $z \lesssim {off_axis_jet_redshift_limit.value:.2f}$")

VLA can detect newtownian outflows at $z \lesssim 0.15$
VLA can detect relativistic outflows at $z \lesssim 2.08$
VLA can detect off-axis relativistic outflows at $z \lesssim 0.42$

In [7]:
meta[(meta.redshift < off_axis_jet_redshift_limit) * (meta.name.str.startswith("SDSS"))]

,name,ra,ra_unit,dec,dec_unit,coord_bibcode,ecl_discovery_date,discovery_date,discovery_date_format,discovery_date_bibcode,redshift,redshift_bibcode,classification,classification_bibcode,radio_data,radio_data_comment,otter,otter_comments,comment
1,SDSS_J0748,07:48:20.6668,hour,+47:12:14.2648,degree,2024MNRAS.535.1095C,2004-02-20,2004-02-20,iso,2024MNRAS.528.7076C,0.0616,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,some xray data is available,Uploader:Noah Franz | Email: nfranz@arizona.edu
2,SDSS_J0807,08:07:27.3157,hour,+14:05:37.0892,degree,2024MNRAS.535.1095C,2005-11-08,2005-11-08,iso,2024MNRAS.528.7076C,0.0738,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
3,SDSS_J0938,09:38:01.6376,hour,+13:53:17.0423,degree,2024MNRAS.535.1095C,2006-12-23,2006-12-23,iso,2024MNRAS.528.7076C,0.1010,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,"Kate, VLASS",False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
4,SDSS_J0952,09:52:09.5629,hour,+21:43:13.2979,degree,2024MNRAS.535.1095C,2005-12-30,2005-12-30,iso,2024MNRAS.528.7076C,0.0795,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,some xray data is available,Uploader:Noah Franz | Email: nfranz@arizona.edu
5,SDSS_J1055,10:55:26.4177,hour,+56:37:13.1010,degree,2024MNRAS.535.1095C,2002-04-09,2002-04-09,iso,2024MNRAS.528.7076C,0.0740,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,"Kate, VLASS",False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
6,SDSS_J1207,12:07:19.8102,hour,+24:11:55.8789,degree,2024MNRAS.535.1095C,2008-01-19,2008-01-19,iso,2024MNRAS.528.7076C,0.0503,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
7,SDSS_J1241,12:41:34.2561,hour,+44:26:39.2636,degree,2024MNRAS.535.1095C,2004-02-27,2004-02-27,iso,2024MNRAS.528.7076C,0.0419,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS, 4 other observations from other p...",False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
8,SDSS_J1247,12:47:26.3719,hour,+07:05:25.0809,degree,2024MNRAS.535.1095C,2006-05-21,2006-05-21,iso,2024MNRAS.528.7076C,0.1040,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
9,SDSS_J1342,13:42:44.4150,hour,+05:30:56.1451,degree,2024MNRAS.535.1095C,2002-04-09,2002-04-09,iso,2024MNRAS.528.7076C,0.0365,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,WISE data from Wang+18,Uploader:Noah Franz | Email: nfranz@arizona.edu
10,SDSS_J1350,13:50:01.4946,hour,+29:16:09.6460,degree,2024MNRAS.535.1095C,2006-04-23,2006-04-23,iso,2024MNRAS.528.7076C,0.0777,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,some xray data is available,Uploader:Noah Franz | Email: nfranz@arizona.edu
11,SDSS_J1402,14:02:04.7560,hour,+29:39:46.8759,degree,2024MNRAS.535.1095C,2007-03-19,2007-03-19,iso,2024MNRAS.528.7076C,0.1960,2024MNRAS.528.7076C,Unkown?,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
12,SDSS_J1459,14:59:26.0676,hour,+40:45:38.5508,degree,2024MNRAS.535.1095C,2004-05-21,2004-05-21,iso,2024MNRAS.528.7076C,0.1510,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
13,SDSS_J1715,17:15:04.2893,hour,+56:47:15.8404,degree,2024MNRAS.535.1095C,2000-09-01,2000-09-01,iso,2024MNRAS.528.7076C,0.1910,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
14,SDSS_J2220,22:20:55.7312,hour,-07:53:17.8464,degree,2024MNRAS.535.1095C,2001-10-21,2001-10-21,iso,2024MNRAS.528.7076C,0.1490,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
15,SDSS_J1458,14:58:49.7267,hour,+19:10:33.5109,degree,2024MNRAS.535.1095C,2008-03-14,2008-03-14,iso,2024MNRAS.535.1095C,0.2680,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,VLASS,True,WISE data from Wang+18,Uploader:Noah Franz | Email: nfranz@arizona.edu
16,SDSS_J1238,12:38:29.5894,hour,+18:52:37.5554,degree,2024MNRAS.535.1095C,2008-01-16,2008-01-16,iso,2024MNRAS.535.1095C,0.2530,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu

In [8]:
radio = pd.read_csv("ecle-radio-photometry.csv", comment="#")
# radio = radio[radio.use_this]

radio[radio.source == "VLASS"]

Empty DataFrame
Columns: [name, day, date, date_format, array_config, filter, filter_eff, filter_eff_units, flux, flux_err, flux_unit, upperlimit, reducer, source, use_this, comments]
Index: []

In [9]:
meta[meta.redshift < relativistic_redshift_limit]

,name,ra,ra_unit,dec,dec_unit,coord_bibcode,ecl_discovery_date,discovery_date,discovery_date_format,discovery_date_bibcode,redshift,redshift_bibcode,classification,classification_bibcode,radio_data,radio_data_comment,otter,otter_comments,comment
0,2019qiz,04:46:37.880,hour,-10:13:34.90,degree,2019TNSTR1857....1F,2020-12-15,2458745.9998032,JD,2019TNSTR1857....1F,0.015100,2019TNSTR1857....1F,TDE,2019TNSCR1921....1S,True,"Kate (very good radio dataset, still need to a...",True,good uvoir dataset,Uploader:Noah Franz | Email: nfranz@arizona.edu
1,SDSS_J0748,07:48:20.6668,hour,+47:12:14.2648,degree,2024MNRAS.535.1095C,2004-02-20,2004-02-20,iso,2024MNRAS.528.7076C,0.061600,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,some xray data is available,Uploader:Noah Franz | Email: nfranz@arizona.edu
2,SDSS_J0807,08:07:27.3157,hour,+14:05:37.0892,degree,2024MNRAS.535.1095C,2005-11-08,2005-11-08,iso,2024MNRAS.528.7076C,0.073800,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
3,SDSS_J0938,09:38:01.6376,hour,+13:53:17.0423,degree,2024MNRAS.535.1095C,2006-12-23,2006-12-23,iso,2024MNRAS.528.7076C,0.101000,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,"Kate, VLASS",False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
4,SDSS_J0952,09:52:09.5629,hour,+21:43:13.2979,degree,2024MNRAS.535.1095C,2005-12-30,2005-12-30,iso,2024MNRAS.528.7076C,0.079500,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,some xray data is available,Uploader:Noah Franz | Email: nfranz@arizona.edu
5,SDSS_J1055,10:55:26.4177,hour,+56:37:13.1010,degree,2024MNRAS.535.1095C,2002-04-09,2002-04-09,iso,2024MNRAS.528.7076C,0.074000,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,"Kate, VLASS",False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
6,SDSS_J1207,12:07:19.8102,hour,+24:11:55.8789,degree,2024MNRAS.535.1095C,2008-01-19,2008-01-19,iso,2024MNRAS.528.7076C,0.050300,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
7,SDSS_J1241,12:41:34.2561,hour,+44:26:39.2636,degree,2024MNRAS.535.1095C,2004-02-27,2004-02-27,iso,2024MNRAS.528.7076C,0.041900,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS, 4 other observations from other p...",False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
8,SDSS_J1247,12:47:26.3719,hour,+07:05:25.0809,degree,2024MNRAS.535.1095C,2006-05-21,2006-05-21,iso,2024MNRAS.528.7076C,0.104000,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
9,SDSS_J1342,13:42:44.4150,hour,+05:30:56.1451,degree,2024MNRAS.535.1095C,2002-04-09,2002-04-09,iso,2024MNRAS.528.7076C,0.036500,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,WISE data from Wang+18,Uploader:Noah Franz | Email: nfranz@arizona.edu
10,SDSS_J1350,13:50:01.4946,hour,+29:16:09.6460,degree,2024MNRAS.535.1095C,2006-04-23,2006-04-23,iso,2024MNRAS.528.7076C,0.077700,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,"Kate, VLASS",True,some xray data is available,Uploader:Noah Franz | Email: nfranz@arizona.edu
11,SDSS_J1402,14:02:04.7560,hour,+29:39:46.8759,degree,2024MNRAS.535.1095C,2007-03-19,2007-03-19,iso,2024MNRAS.528.7076C,0.196000,2024MNRAS.528.7076C,Unkown?,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
12,SDSS_J1459,14:59:26.0676,hour,+40:45:38.5508,degree,2024MNRAS.535.1095C,2004-05-21,2004-05-21,iso,2024MNRAS.528.7076C,0.151000,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
13,SDSS_J1715,17:15:04.2893,hour,+56:47:15.8404,degree,2024MNRAS.535.1095C,2000-09-01,2000-09-01,iso,2024MNRAS.528.7076C,0.191000,2024MNRAS.528.7076C,AGN,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
14,SDSS_J2220,22:20:55.7312,hour,-07:53:17.8464,degree,2024MNRAS.535.1095C,2001-10-21,2001-10-21,iso,2024MNRAS.528.7076C,0.149000,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
15,SDSS_J1458,14:58:49.7267,hour,+19:10:33.5109,degree,2024MNRAS.535.1095C,2008-03-14,2008-03-14,iso,2024MNRAS.535.1095C,0.268000,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,VLASS,True,WISE data from Wang+18,Uploader:Noah Franz | Email: nfranz@arizona.edu
16,SDSS_J1238,12:38:29.5894,hour,+18:52:37.5554,degree,2024MNRAS.535.1095C,2008-01-16,2008-01-16,iso,2024MNRAS.535.1095C,0.253000,2024MNRAS.528.7076C,TDE,2024MNRAS.528.7076C,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
17,AT2017gge,16:20:34.99,hour,+24:07:26.5,degree,2022MNRAS.517...76O,2018-03-09,2457968.8499884,JD,2017TNSTR.895....1T,0.066500,2022MNRAS.517...76O,TDE,2022MNRAS.517...76O,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
18,AT2022fpx,15:31:03.698,hour,+53:24:19.13,degree,2022TNSTR.836....1T,2022-08-05,2459670.01981,JD,2022TNSTR.836....1T,0.073000,2022TNSCR1771....1P,TDE,2022TNSCR1771....1P,True,VLASS,True,no phot,Uploader:Noah Franz | Email: nfranz@arizona.edu
19,AT2022upj,00:23:56.86,hour,-14:25:23.4,degree,2024MNRAS.535.1095C,2022-11-02,2459822.878,JD,2022TNSTR2690....1F,0.054000,2024MNRAS.535.1095C,TDE,2024MNRAS.535.1095C,True,VLASS,True,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
20,AT2021dms,03:21:24.069,hour,-11:08:45.71,degree,2024MNRAS.528.4775H,2021-08-13,2459266.645706,JD,2021TNSTR.542....1F,0.031102,2024MNRAS.528.4775H,TDE,2024MNRAS.528.4775H,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
21,AT2018bcb,22:43:42.871,hour,-16:59:08.49,degree,2020MNRAS.494.2538N,2018-05-13,2458235.62,JD,2018TNSTR.555....1B,0.119200,2020MNRAS.494.2538N,TDE,2020MNRAS.494.2538N,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
22,AT2020vdq,10:08:53.44,hour,+42:43:00.22,degree,2020TNSTR3060....1N,2022-02-06,2459126.9916204,JD,2020TNSTR3060....1N,0.045000,2023arXiv231003782S,TDE,2023arXiv231003782S,True,VLASS,True,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
23,AT2021qth,20:11:38.914,hour,-21:09:36.83,degree,2021TNSTR2141....1F,2022-05-26,2459382.9156134,JD,2021TNSTR2141....1F,0.080500,2023ApJ...955L...6Y,TDE,2023ApJ...955L...6Y,True,VLASS,True,no phot,Uploader:Noah Franz | Email: nfranz@arizona.edu
24,AT2021acak,10:34:47.99,hour,+15:29:22.42,degree,2023RAA....23b5012L,2022-04-23,2459510.12,JD,2021TNSTR3613....1T,0.136000,2023RAA....23b5012L,TDE,2023RAA....23b5012L,True,VLASS,False,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
25,AT2018dyk,15:33:08.015,hour,+44:32:08.20,degree,2018TNSTR.987....1F,2018-08-08,2458269.81,JD,2018TNSTR.987....1F,0.037000,2018TNSCR1182....1H,TDE,2018TNSCR1182....1H,True,VLASS,True,NaN,Uploader:Noah Franz | Email: nfranz@arizona.edu
26,AT2018gn,01:46:42.45,hour,+32:30:29.30,degree,2018TNSTR..58....1K,2022-06-29,2458132.61,JD,2018TNSTR..58....1K,0.037500,2024ApJ...966..136W,TDE,2024ApJ...966..136W,True,VLASS,True,good optical,Uploader:Noah Franz | Email: nfranz@arizona.edu